### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by pantherale0** [pantherale0/haanglianwater#45]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Well, that lasted long, seems like AW have replaced their mobile app. I will see if that app is as easy to manipulate as the old one or if they have changed the protocols entirely.

In the meantime, perhaps good to tweet AW (@ AnglianWater)  for an official API?

### Reproduction steps

N/A

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 09:30:49 (1 occurrences)
Last logged: 09:30:49

Error setting up entry ....... for anglian_water
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anglian_water/__init__.py", line 42, in async_setup_entry
    _api = await API.create_via_login_existing_device(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/api.py", line 121, in create_via_login_existing_device
    await self.refresh_login()
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/api.py", line 126, in refresh_login
    resp = await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyanglianwater/api.py", line 181, in send_request
    resp_body = await _response.json()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1194, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://myaccount.anglianwater.co.uk')
```

**Comment by pantherale0** [comment]
Ok, looks like they have moved over to use Azure B2C for auth, and pretty much just wrapped a website in the mobile app.
